### ISSUE TITLE
编译不过了

### ISSUE THREAD

**Issue by Bupterambition** [c98/AppMateServer#1]
inking ./.build/x86_64-apple-macosx10.10/debug/PerfectTemplate
ld: library not found for -lCHTTPParser for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/bob/Git/MyRepos/AppMateServer/.build/debug.yaml main

**Comment by c98** [comment]
好长时间没看了 😅。

这个问题是 swift 4 环境编译的问题，刚刚更新了相关配置 😁。

@Bupterambition 如果没有问题的话，我就关闭这个 issue 了。
